import network from "./network";
export const login = (data={})=>network.post("/login",data)
export const register = (data={})=>network.post("/register",data)
export const getUsers = (data = {})=>network.get('/app/v1/getUser', data)
export const createUser = (data = {})=>network.post('/app/v1/createUser', data)
export const updataUser = (data = {})=>network.put('/app/v1/updateUser', data)
export const deleteUser = (data = {})=>network.delete(`/app/v1/deleteUser/${data}`)
export const getGoods = (data = {})=>network.get('/app/v1/getGoods', data)
export const addGood = (data = {})=>network.post('/app/v1/addGoods', data)
export const altGood = (data = {})=>network.put('/app/v1/altGood', data)
export const delGood = (data = {})=>network.delete('/app/v1/delGood', data)
export const getSubCategory = (data = {})=>network.get('/app/v1/getSubCategory', data)
export const getCategory = (data = {})=>network.get('/app/v1/getCategory', data)
export const addCategory = (data = {})=>network.post('/app/v1/addCategory', data)
export const alterCategory = (data = {})=>network.put('/app/v1/alterCategory', data)
export const deleteCategory = (data = {})=>network.delete('/app/v1/delCategory',data)
export const altSku = (data = {})=>network.put('/app/v1/altSku', data)
export const altPprice = (data = {})=>network.put('/app/v1/altpprice', data)
export const getOrder = (data = {})=>network.get('/app/v1/getorder', data)
export const altOrderState = (data = {})=>network.put('/app/v1/altorderstate', data)